# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Debtdrone < Formula
  desc "Technical debt analysis tool for modern codebases."
  homepage "https://github.com/endrilickollari/debtdrone"
  version "0.6.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/endrilickollari/debtdrone-cli/releases/download/v0.6.3/debtdrone_Darwin_x86_64.tar.gz"
      sha256 "5c909da9d212b773bf96322bc10a9f2508a22b776a7a7f64878a8f3a49cd8e2e"

      def install
        bin.install "debtdrone"
      end
    end
    on_arm do
      url "https://github.com/endrilickollari/debtdrone-cli/releases/download/v0.6.3/debtdrone_Darwin_arm64.tar.gz"
      sha256 "86f5d969c62d2abebba39d3676578e07dc27a2664fe91f449b910c7647da509c"

      def install
        bin.install "debtdrone"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/endrilickollari/debtdrone-cli/releases/download/v0.6.3/debtdrone_Linux_x86_64.tar.gz"
        sha256 "901fa8ed3ab3beeab7c3949abba2b666dd5e4fcb303ec1aad950a5142860843d"

        def install
          bin.install "debtdrone"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/endrilickollari/debtdrone-cli/releases/download/v0.6.3/debtdrone_Linux_arm64.tar.gz"
        sha256 "fade8dd1807c2ff03ba5104a0252203897981927ef0cf592669f5f0a7d1022fc"

        def install
          bin.install "debtdrone"
        end
      end
    end
  end

  test do
    system "#{bin}/debtdrone --version"
  end
end
